name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-core:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # or the version you're using

    - name: Restore dependencies
      run: dotnet restore ./GenericModEngine.Core

    - name: Build in Release mode
      run: dotnet build ./GenericModEngine.Core --configuration Release

    - name: Check build status
      run: |
        if [ $? -ne 0 ]; then
          echo "Build failed!"
          exit 1
        fi


  test:
    needs: [build-core]  # Make sure the build job is completed before running tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # or the version you're using

    - name: Run tests
      run: dotnet test

    - name: Check test status
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed!"
          exit 1
        fi
